# Generated by Django 3.2.8 on 2021-10-20 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtext', models.TextField(max_length=4000)),
                ('faction', models.CharField(blank=True, choices=[('AB', 'Autobot'), ('DC', 'Decepticon'), ('MR', 'Mercenary')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Battle Card Type',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare')], max_length=2)),
                ('cardnum', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.card')),
            ],
        ),
        migrations.CreateModel(
            name='CharCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('AB', 'Autobot'), ('DC', 'Decepticon'), ('MR', 'Mercenary')], max_length=2)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.card')),
            ],
            options={
                'verbose_name': 'Character',
            },
        ),
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('O', 'Orange'), ('U', 'Blue'), ('B', 'Black'), ('W', 'White'), ('G', 'Green')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StratCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('cardtext', models.TextField(max_length=4000)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.card')),
                ('charcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.charcard')),
            ],
            options={
                'verbose_name': 'Stratagem',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('cards', models.ManyToManyField(through='carddb.CardSet', to='carddb.Card')),
            ],
        ),
        migrations.CreateModel(
            name='PipSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.battlecard')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.pip')),
            ],
        ),
        migrations.AddField(
            model_name='pip',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.trait'),
        ),
        migrations.CreateModel(
            name='CharSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ALT', 'Alt Mode'), ('BOT', 'Bot Mode'), ('BODY', 'Body Mode'), ('HEAD', 'Head Mode'), ('LEGD', 'Legend Mode'), ('COMB', 'Combiner Mode'), ('UPGR', 'Upgrade Mode')], max_length=4)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('health', models.IntegerField()),
                ('cardtext', models.TextField(max_length=4000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.charcard')),
                ('traits', models.ManyToManyField(to='carddb.Trait')),
            ],
            options={
                'verbose_name': 'Character Mode',
            },
        ),
        migrations.AddField(
            model_name='cardset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.set'),
        ),
        migrations.CreateModel(
            name='BCardSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carddb.bcardtype')),
            ],
            options={
                'verbose_name': 'Battle Card Subtype',
            },
        ),
        migrations.AddField(
            model_name='battlecard',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carddb.card'),
        ),
        migrations.AddField(
            model_name='battlecard',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='carddb.BCardSubtype'),
        ),
        migrations.AddField(
            model_name='battlecard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carddb.bcardtype'),
        ),
    ]
