version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    container_name: django_web
    extra_hosts:
      - "database:192.168.1.16"
    volumes:
      - ./seekerdb:/app
    ports:
      - "8080:8080"
